/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dbconnection.DBConnection;
import javax.swing.*;
import useradministration.User;

/**Plan
 * Every form inherits from Form, PURELY in the interest of limiting testing time of dynamically swapped JPanels. goddamnit.
 * A Form.field for holding a reference to the user.
 * A user class that holds and returns all information on a user.
 * Logging in.
 */

/**
 *
 * @author alessandrobisiani
 */
public class Form extends JFrame {
    
    private static DBConnection dbConnection;
    private static User user;

    /**
     * Creates new form Form
     */
    public Form(/**User user*/) {
        this.user = user;
        initComponents();
    }

    public void logout(){
        user = null;
        new LoginPage().setVisible(true);
        this.dispose();
    }

    public void exit(){
        System.exit(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(332, 332, 332)
                .add(jButton1)
                .addContainerGap(498, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(128, 128, 128)
                .add(jButton1)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        logout();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}

